### ISSUE TITLE
XGrammar Feature Tracking

### ISSUE THREAD

**Issue by Ubospica** [mlc-ai/xgrammar#15]
- [ ] Tests for generation of common models
- [x] Further integration with MLC-LLM
- [x] Caching policy
- [x] ApplyMask operator
- [x] Documentation refinement
- [ ] Support for regex and optimization
- [ ] Grammar construction: string, multiple choices
- [ ] Grammar manipulation: add
- [ ] Grammar construction: function signature, template
- [ ] Further support for jumpforward decoding: retokenization
- [ ] Support for (parallel) tool calling
- [ ] New fsm backend: faster and more flexible
- [ ] More optimization passes
- [x] language frontend: gbnf
- [ ] language frontend: lark
- [x] Error reporting
- [ ] README.md
- [ ] ApplyMask kernel
- [ ] Upload to pypi
